### ISSUE TITLE
Please check your credentials

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.libre#15]
Hallo,
im log kommt:
Login failed. Please check your credentials and login to the app and accept the terms of use.

Terms wurden aber akzeptiert.

vgl. auch:
https://forum.iobroker.net/topic/55443/test-freestyle-libre-librelinkup/176?_=1727503267667

**Comment by TA2k** [comment]
Kann ich nicht nachvollziehen nach logout und login in der App geht alles

**Comment by bahnuhr** [comment]
Hast recht,
diesen Schritt hatte ich wohl dann nicht gemacht.
