### ISSUE TITLE
Please update the version in the settings with the current version of the app

### ISSUE THREAD

**Issue by bahnuhr** [TA2k/ioBroker.libre#17]
Hallo,
seit heute kommt im log:
Please update the version in the settings with the current version of the app

Installiert habe 0.1.1
Am Handy die librelinkup mit V 4.12.0
(auch so in der Instanz eingegeben).
Ansonsten das gleiche Fehlerbild wie im Forum:
https://forum.iobroker.net/topic/55443/test-freestyle-libre-librelinkup/178?_=1731647992208

Instanz ist grün.
Daten kommen aber nicht an.

mfg
Dieter

**Comment by mllrmnn** [comment]
Hi, ich habe exakt das gleiche Problem

**Comment by bullenauge** [comment]
Same here, 15.11. um 12:01 Uhr.

**Comment by TA2k** [comment]
Please test v0.1.2

**Comment by TA2k** [comment]
v0.1.3

**Comment by bullenauge** [comment]
Ok bei mir.
Besten Dank für den flotten fix.

**Comment by mllrmnn** [comment]
Bei mir funktioniert es auch wieder

**Comment by bahnuhr** [comment]
ja, läuft
Danke

**Comment by svenlohberg** [comment]
Vielen Dank für das schnelle Erstellen der neuen Version!
