### ISSUE TITLE
libre is not provided anymore in iobroker    

### ISSUE THREAD

**Issue by sir0drake** [TA2k/ioBroker.libre#18]
Hi,
i am also affected with the behavior in #17.
will update/upgrade to 0.1.3
but libre ist not anymore listed in adapters
after delete adapter 0.1.1 also not beeing able 
to install 0.1.2 by file from command by npm

can you pls check the release-repository
to be able to install the adapter fresh from iobroker

thanks in advance

![image](https://github.com/user-attachments/assets/3f197de7-7171-409f-b657-08e610983f07)

**Comment by TA2k** [comment]
switch to latest/beta repo

**Comment by sir0drake** [comment]
Thanks TA2k

but again, Libre ist not anymore listed in iobroker adapters.

No chance to install it.
not in stable nor in beta

Once it's deinstalled ( done by me ) 
no way to install it.

![image](https://github.com/user-attachments/assets/2b58a52e-0810-4938-8398-3c56b8122f16)

**Comment by TA2k** [comment]
You have to wait a few hours
You can install via GitHub symbol 
<img width="36" alt="image" src="https://github.com/user-attachments/assets/24cde218-06f1-497e-82cd-ae73499d7eca">

**Comment by sir0drake** [comment]
thanks for info   

will wait and install later the day

rgds

**Comment by sir0drake** [comment]
it's done !
works fine with v0.1.3
This piece of software is really very helpful. 
As someone affected, I can only thank you!

rgds
